### ISSUE TITLE
Réduire la taille de l'image d'accueil

### ISSUE THREAD

**Issue by ElTyranos** [Vernam/vernam.github.io#2]
Elle doit faire 1200 de haut, il faut réduire en dessous de 1080 (900 ?) pour raccourcir le scroll sur les résolution inférieures.

**Comment by Vernam** [comment]
Idéalement, c'est 960px, l'image que tu m'a donné fait 900.

La barre grise du haut, je sais pas pourquoi elle est la, je fais des tests

**Comment by ElTyranos** [comment]
parce que l'image fait 900 donc elle est centrée verticalement

**Comment by Vernam** [comment]
C'est fixe :)
